### ISSUE TITLE
Marketplace - Master 

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/nft#3]
OpenSea Doc: https://docs.opensea.io/docs/3-viewing-your-items-on-opensea

### Pages 
- [x] **Remco**: Landingpage 💪
- [x] **Remco**: FAQ
- [x] **Remco**: Marketplace
- [x] Contact Us
- [x] My NFTs (name is just a suggestion)

### Components
- [x] Header
- [x] Footer (Clélia)
- [x] **Samir** Connect to Web3 Button (Maybe it would be nice if we could connect to the users meta mask and show him his NFTs)

### Lib/Service
- [x] Web3Service that handles the connection

### Type of ERC
- [ ] ERC721
- [x] ERC1155

**Comment by SamirTouira** [comment]
i cannot edit, so i put my name here.
![image](https://user-images.githubusercontent.com/52285231/114681734-b95e4c80-9d0e-11eb-9a70-bba638d2d1d4.png)

- [ ]  Connect to Web3 Button (Maybe it would be nice if we could connect to the users meta mask and show him his NFTs) (Samir)

**Comment by RemcoSimonides** [comment]
- [x] **Remco**: Add My Tokens to My Tokens page
- [x] **Samir**: Listener for metamask account changes
- [x] **Mano**: Fix height of page so footer is on the bottom again
- [ ] Replace marketplace with our own components (break down into smaller tasks)
- [ ] Create multiple sales when minting a token
- [ ] Add store for Vanity tokens
- [ ] My tokens page doesn't listen to metamask account changes yet, would be nice to listen and get their tokens again
