### ISSUE TITLE
Un-Hide Marketplace

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/nft#94]
Marketplace have been hidden to prevent users seeing an empty store.
Now that we have minted some NFTs, we should un-hide the marketplace.

- [ ] Un-comment the "marketplace" button on the header
- [ ] Change landing CTA link to redirect to `/marketpalce`
- [ ] Change CTA text to "Enter the Marketplace"

Look for `TODO issue#94` in the code to find the places to update

**Comment by phpgeekfr** [comment]
Marketplace was removed. see https://github.com/blockframes/nft-lab/issues/130
